#!/usr/bin/env ruby
# frozen_string_literal: true

project_lib = File.expand_path("../src", __dir__)
$LOAD_PATH.unshift(project_lib) if Dir.exist?(project_lib) && !$LOAD_PATH.include?(project_lib)

ARGV.each_with_index do |argument, index|
  if argument == "--config"
    abort "quarks: --config requires a path" unless ARGV[index + 1]
    ENV["QUARKS_CONFIG"] = ARGV[index + 1]
    ARGV.slice!(index, 2)
    break
  elsif argument.start_with?("--config=")
    ENV["QUARKS_CONFIG"] = argument.delete_prefix("--config=")
    ARGV.delete_at(index)
    break
  end
end

if ARGV.length == 1 && %w[version --version].include?(ARGV.first)
  require "quarks/fast_cli"
  if Quarks::FastCLI.safe_version_path?
    Quarks::FastCLI.version
    exit 0
  end
end

begin
  require "quarks"
rescue Quarks::Config::Error => e
  warn "quarks: #{e.message}"
  exit 2
end

Quarks::CLI.new.run(ARGV)
